### ISSUE TITLE
about exp folder

### ISSUE THREAD

**Issue by ramge132** [bahjat-kawar/ddrm#14]

**Comment by Ramge132** [comment]
I solved a few things while studying, but I got another question.

## Resolved
### 1. /exp/datasets/imagenet/imagenet
I realized that I had to download the dataset myself and place it in the `exp/` folder. 
(imagenet = imagenet ILSVRC2012 validation data)
 
## 2. imagenet_val_1k.txt
I realized that the `imagenet_val_1k.txt` file should be imported from 
github.com/XingangPan/deep-generative-prior/

## New Issue
I don't know where to Download the datasets below.
- odd
- odd_bedroom
- od_cat
- od_celeba 

Thank you so much.

**Comment by Ceeeeeeeeb** [comment]
> Hi, Ramge132, it seems that all these four datasets could be download from this link:
https://github.com/jiamings/ddrm-exp-datasets
which is in the readme.
