### ISSUE TITLE
VE implementation

### ISSUE THREAD

**Issue by UdonDa** [bahjat-kawar/ddrm#2]
Hi, @bahjat-kawar 

Thank you for sharing your nice implementation!
I guess that your code includes only VP SDEs.
Would you provide a code for VE SDEs?

**Comment by bahjat-kawar** [comment]
Hello,
The sampling used in the code is similar to VE SDEs, but the model is trained using VP SDEs.
We currently do not have plans to provide further code, but switching between VE and VP should be fairly simple. Please check out the appendix in the paper that explains how VE and VP are related.
