### ISSUE TITLE
Using existing blurred image as input

### ISSUE THREAD

**Issue by cyprian** [bahjat-kawar/ddrm#3]
Thank you for your awesome work!

I would like to test the diffusion from an input image. 
Example. I create a blurry image then use a diffusion model to clean it. 
By looking at your code for de-blurring, you take clear images from a folder and auto blur them before you do diffusion.
Is there a way to just use my already blurred input image? Or do I have to change the code to do that?

Thank you.

**Comment by bahjat-kawar** [comment]
The current code requires the original image for PSNR evaluation. If you want to apply it on an already blurred image without evaluation, a few changes to the code would be necessary. You would also need to make sure the code uses the correct blurring kernel.

**Comment by malekinho8** [comment]
Was anyone ever able to figure out how to implement this in the code? I have been looking through the code for hours debugging line by line, and I'm still not sure if it is possible. Any help or hints on this would be greatly appreciated.
